spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbhonichau/mbhoni-es
          search-paths: config
          clone-on-start: true
          skip-ssl-validation: false   # SECURE
          username: mbhonichau
          password: ${GITHUB_TOKEN}    # Injected via env
  profiles:
    active: git

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoint:
    health:
      validate-group-membership: false
